### PR TITLE
Fix `._orig` access for submodules for MF extensions

### PR DESCRIPTION
**Pull request by romain-intel**
This addresses an issue where submodules like `mymodule._orig.submodule` would not load properly.

This will properly load things like `from .foofa import xyz` from a module or sub-module in the original location but currently does not work if the import path is absolute.

### CODE REVIEW

**Review by roofurmston — COMMENTED** [review]
Not an expert with the inner working of the Python import system, so learnt a lot from the PR. :)

the PR looks good to me. 

The one thing I wonder is if the changes merit some additional tests. You think it is worth adding some? Would be happy to have a stab at adding some, if you think it is worthwhile.

**Comment by romain-intel** [comment]
Yep. I think tests would be nice. THere are some unit tests that test the extension mechanism. We can just add an extension that overrides something simple and see if we can access _orig. Would you be able to do that? Happy to provide pointers. And don't feel obligated, if you don't have time, I can do it too :).

**Comment by roofurmston** [comment]
> Yep. I think tests would be nice. THere are some unit tests that test the extension mechanism. We can just add an extension that overrides something simple and see if we can access _orig. Would you be able to do that? Happy to provide pointers. And don't feel obligated, if you don't have time, I can do it too :).

Yeah, would be very happy to have a go at it :)

I'll have a crack at it next week.

**Comment by tfurmston** [comment]
OK, so I've had a go at adding a test case. I picked the most innocuous looking module to extend.

The attempt is here, if you want to have a look - [https://github.com/Netflix/metaflow/pull/1192](https://github.com/Netflix/metaflow/pull/1192). Still waiting for the tests to start in CI, but I checked the `ExtensionsTest` locally and it went through fine. 

One thing I wasn't sure about, will the `frameworks` module be extended just for the `ExtensionsTest` test? Or will it be for all test casses?

**Review by savingoyal — APPROVED** [review]

**Pull request merged**
