### PR TITLE
Add tags to `current` singleton

### PR DESCRIPTION
**Pull request by sam-watts**

### CODE REVIEW

**Comment by sam-watts** [comment]
Tests run for all graphs on updated `CurrentSingletonTest` at least, didn't have time to run all tests locally

**Comment by savingoyal** [comment]
@sam-watts Thanks for the PR. It looks good to go and we can merge it as soon as the tests pass. One point that I would like to call out is that we will soon allow tag mutations and theoretically, the tags can be modified for an inflight run but the new values won't show up in the `current` object.

**Review by savingoyal — APPROVED** [review]

**Comment by savingoyal** [comment]
@sam-watts In case you are interested - #1017 is a very similar issue that needs to be resolved :) Would you like to make a PR for that as well?

**Comment by sam-watts** [comment]
@savingoyal I want to get familiar with the codebase so more than happy to have a crack at https://github.com/Netflix/metaflow/issues/1017 too 😄

**Pull request merged**
