### PR TITLE
Typo repair and PEP8 cleanup

### PR DESCRIPTION
**Pull request by jimbudarz**
I've made a number of changes to address misspellings, grammar issues, and other text-things that needed clarified.
I was pretty aggressive, so please feel free to reject anything that you don't agree with!

Some of the changes were made to function names with clear misspellings (i.e. "kubernetes" spelled as "kuberentes")

### CODE REVIEW

**Review by savingoyal — CHANGES_REQUESTED** [review]
lgtm! if you can remove `metaflow/_vendor` from this PR, we should be good to go!

**Comment by jimbudarz** [comment]
Sure thing, @savingoyal . I believe I've reverted the changes to that folder now.

**Comment by jimbudarz** [comment]
`black` is failing, so I'm going to revert some controversial changes (black vs pep8 vs flake8 and [whitespace](https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated))

**Review by savingoyal — APPROVED** [review]

**Comment by savingoyal** [comment]
@jimbudarz The changes to `metaflow/_vendor` are still present in the PR. Can you leave them out?

**Comment by jimbudarz** [comment]
Ugh, they're actually _back_ because I ran `black` on the whole repo. 
So sorry.

**Comment by romain-intel** [comment]
black is still not happy (i think it's because we may be using an older version. @savingoyal , maybe we can update to the newer version. There used to be a bug with the newer one at some point (click thing) but I think they fixed it. The newer version and older version differ in particular on the spacing around "**" which is what the errors here are listing.

**Comment by savingoyal** [comment]
@romain-intel bumped the version of black to latest here in https://github.com/Netflix/metaflow/pull/1198

**Comment by savingoyal** [comment]
@jimbudarz can you rebase this PR, now that #1199 has been merged?

**Comment by romain-intel** [comment]
Black is happy now. Failures on 3.5 and 3.6 seem to be a GitHub actions fluke; I'll retrigger when the rest is done.

**Comment by jimbudarz** [comment]
@romain-intel It looks like the GitHub Action is [failing](https://github.com/actions/setup-python/issues/544) due to migration to Ubuntu 22.04. A workaround is to hard-code `ubuntu-20.04` instead of `ubuntu-latest`.

**Comment by savingoyal** [comment]
@jimbudarz hopefully #1201 should fix the issue.

**Comment by romain-intel** [comment]
yep. we are making the changes.

**Comment by romain-intel** [comment]
I'm going to merge this in for now though since tests seem to pass on 3.5 and 3.6 (for mac) to save you the trouble of having to rebase yet again. Discussed with @savingoyal offline and we are in agreement.

**Pull request merged**
