### PR TITLE
Follow symlinks while packaging code for execution on AWS Batch

### PR DESCRIPTION
**Pull request by savingoyal**
More context in #176

### CODE REVIEW

**Comment by kemalty** [comment]
Hey Savin - Thank you for all the help. I tested the change and here is how it goes:

My test script:

```
    @step
    def start(self):
        self.data = random.randint(0, 100)
        self.next(self.process)

    @step
    def process(self):
        self.data /= 100
        self.next(self.symlink_check_local)

    @step
    def symlink_check_local(self):
        with open("xxx/xxx/symbolic_links/test_symlink.sl", "r") as f:
            symlink_txt = f.readlines()
        print(symlink_txt)
        self.next(self.symlink_check_batch)

    @batch(cpu=1, memory=1000)
    @step
    def symlink_check_batch(self):
        print(os.system("ls"))
        print(os.system("ls symbolic_links/"))
        with open("symbolic_links/test_symlink.sl", "r") as f:
            symlink_txt = f.readlines()
        print(symlink_txt)
        self.next(self.end)

    @step
    def end(self):
        print(self.data)
        print("🏁🏁🏁🏁🏁🏁🏁🏁🏁")
```


Here is the command:

`python xxx/xxx/hello_metaflow.py --package-suffixes '.py,.json,.sql,.sl,.txt' run | tee out.txt`

So the symlink was in `xxx/xxx/symbolic_links/test_symlink.sl`, and it was pointing a file in the root directory called `test.txt` written hello world text in it.

Here is the shortened output:

```
Metaflow 2.0.3.post2+gitb4a2eeb executing MockFlow for user:kemalty
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
Following Links...
Following Links...
2020-04-10 15:13:01.768 Workflow starting (run-id 194):
2020-04-10 15:13:02.304 [194/start/1366 (pid 42637)] Task is starting.
2020-04-10 15:13:05.868 [194/start/1366 (pid 42637)] Task finished successfully.
2020-04-10 15:13:06.582 [194/process/1367 (pid 42645)] Task is starting.
2020-04-10 15:13:10.483 [194/process/1367 (pid 42645)] Task finished successfully.
2020-04-10 15:13:11.226 [194/symlink_check_local/1368 (pid 42652)] Task is starting.
2020-04-10 15:13:13.623 [194/symlink_check_local/1368 (pid 42652)] ['Hello symlink...\n']
2020-04-10 15:13:14.704 [194/symlink_check_local/1368 (pid 42652)] Task finished successfully.
2020-04-10 15:13:15.456 [194/symlink_check_batch/1369 (pid 42662)] Task is starting.
2020-04-10 15:13:16.267 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Task is starting (status SUBMITTED)...
2020-04-10 15:13:20.665 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Task is starting (status RUNNABLE)...
2020-04-10 15:13:22.867 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Task is starting (status STARTING)...
2020-04-10 15:13:26.197 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Task is starting (status RUNNING)...
2020-04-10 15:13:32.074 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Setting up task environment.
2020-04-10 15:13:44.618 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Downloading code package.
2020-04-10 15:13:44.618 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Code package downloaded.
2020-04-10 15:13:44.618 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] Task is starting.
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] INFO
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] __init__.py
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] configs
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] data
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] experiment_main.py
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] hello_metaflow.py
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] job.tar
2020-04-10 15:13:44.619 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] metaflow
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] project_root.py
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] sql
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] src
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] symbolic_links
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] test
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] 0
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] test_symlink.sl
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] 0
2020-04-10 15:13:44.620 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424] <flow MockFlow step symlink_check_batch> failed:
2020-04-10 15:13:44.621 [194/symlink_check_batch/1369 (pid 42662)] [28f3b894-9b70-48f8-a832-d3261c5d2424]     Internal error
a832-d3261c5d2424] FileNotFoundError: [Errno 2] No such file or directory: 'symbolic_links/test_symlink.sl']
2020-04-10 15:13:47.752 [194/symlink_check_batch/1369 (pid 42662)] Task failed.
2020-04-10 15:13:47.752 Workflow failed.
2020-04-10 15:13:47.752 Terminating 0 active tasks...
2020-04-10 15:13:47.752 Flushing logs...
    Step failure:
    Step symlink_check_batch (task-id 1369) failed.
```

So it works fine in local 👍

However, you can see here that the symlinked file is not moved to the batch environment. It is not in the root folder, or in the symlink folder.

As an idea, maybe Metaflow can benefit from the Docker/git kind of approach when moving files. So by default, it moves all the files, with exceptions listed in `.metaflowignore`?

**Comment by savingoyal** [comment]
Ah I missed a case. Let me push out a fix.

**Comment by savingoyal** [comment]
@kemalty Given that this PR is not a blocker right now for your use case, we are going to punt it at the moment. This needs a bit more thought around packaging (particularly around traversing circular links).

**Comment by GregHilstonHop** [comment]
@savingoyal Can you elaborate on your thoughts regarding packing and traversing circular links?

I ended up making this change to my local package to resolve importing some remote code before realizing this PR even existed. I was planning on creating a PR with this exact code change.

**Comment by savingoyal** [comment]
@GregHilstonHop It's not straightforward to detect and traverse circular links. That was the reason for punting this PR.

**Comment by GregHilstonHop** [comment]
@savingoyal Understood. For clarity, if we enable symlink following the desired behavior is to detect and not travese circular links correct? Perhaps some exception is raised?

**Comment by dpatschke** [comment]
I would like to upvote support for this functionality. I currently have a Flow subclass in its own file that I would like to use across multiple flows and thought I was being smart by storing it in a central location in my repo and then symlinking to it only to find out Metaflow doesn't handle this.

Is there another suggested method that Metaflow supports that doesn't require having multiple hard copies of the same file in multiple directories alongside with their accompanying Flow files for something like subclassing?

**Comment by JSpenced** [comment]
@dpatschke Did you figure out a way around this as I was thinking to do the same thing?? 

@savingoyal Any roadmap for re-looking at this? I could possibly help with the fix.

**Comment by tuulos** [comment]
@JSpenced @dpatschke @GregHilstonHop @kemalty I'm happy to let you know that the latest version of Metaflow (2.5.2) follows symlinks in packaging 🎉 We added a bit extra logic to detect symlink cycles which otherwise would have made it hang

**Pull request closed without merging**
