### PR TITLE
except block should only run on an import error

### PR DESCRIPTION
**Pull request by chrisaddy**

### CODE REVIEW

**Comment by mpkocher** [comment]
Related #9

**Comment by savingoyal** [comment]
Thanks for the PR! Much appreciated! Please refer to the [contributing guide](https://github.com/Netflix/metaflow/blob/master/CONTRIBUTING.md). We are aligning internally on how to make contributing to Metaflow easy and transparent.

**Comment by seeravikiran** [comment]
Thanks for making this PR. I would personally prefer that you at least fix some of our other occurrences for `python2 vs python3` ImportError in some other parts of the code base as well; if you're anyway intending to fix this for us.

https://github.com/Netflix/metaflow/search?q=except%3A&unscoped_q=except%3A

I don't mean for you to fix all naked exceptions in our codebase, but there are at least a few more (like `util.py`) which have very similar logic.

@chrisaddy Let me know what you think.

**Comment by chrisaddy** [comment]
@seeravikiran happy to help! I know it's a very small thing, don't want to make pointlessly small PRs, but I'm of the philosophy of clean up small things as you see them. I'll take a look at more exceptions

**Pull request merged**
