### PR TITLE
Verify code hash

### PR DESCRIPTION
**Pull request by ruial**
This PR addresses issue https://github.com/Netflix/metaflow/issues/1172

By verifying the code SHA after it is downloaded, we have additional guarantees that the pipeline code was not tampered with. I've tested this simple implementation with success, both sha1sum and cut are available in the default Python docker image.

### CODE REVIEW

**Comment by savingoyal** [comment]
@ruial Can you provide a bit more context on the tamper-proof guarantees that you are seeking from Metaflow?

**Comment by ruial** [comment]
Hey @savingoyal I expect Metaflow to not execute the code from S3 if it doesn't match the hash defined in the step functions, as mentioned in the issue. This situation can happen when Metaflow is deployed in a shared AWS environment, where multiple teams use the same UI and S3 bucket but have the Batch clusters and Step functions in different accounts. If I wanted, I could replace other teams code and it will be executed in their compute without this fix.

Another great feature for Metaflow would be to allow people to optionally specify a different S3 bucket per flow/experiment, like MLflow does, providing additional security and control over object lifecycle for teams. I would be happy to talk more about this topic and other possible improvements via Slack if you'd like.

**Comment by romain-intel** [comment]
As a quick note, you can specify the bucket you want to use by using the `METAFLOW_DATASTORE_SYSROOT_S3` environment variable.

**Comment by ruial** [comment]
Thanks for the note @romain-intel. I assumed the Metaflow UI was only able to read from a single S3 bucket because a single bucket was set for the UI on the Terraform module https://github.com/outerbounds/terraform-aws-metaflow/blob/master/modules/ui/locals.tf#L26. Does the UI support multiple buckets? I don't remember if I tested it but I will soon.

I still think the code tarball hash should still be checked, as it is already there anyway.

**Comment by romain-intel** [comment]
The UI should work. I remember we ran into this issue a while back and fixed it but can't find the relevant PR. Let me know if it doesn't work.

**Comment by ruial** [comment]
I can confirm that the latest UI works with different S3 buckets, the ```METAFLOW_``` variables are not needed on the backend service. 

This is great, as I no longer have a reason to share an S3 bucket with other accounts/teams. We have a central Metaflow UI, however each team has their own compute/s3/scheduler. By sharing read access to their S3 buckets, other teams can allow us to see their logs/cards from a single UI.

Thanks you guys. Since S3 write access is not shared anymore, there is no risk of someone changing the code tarballs. It may still be considered a good practice to check the hash, but I no longer see this as a security issue for my setup, feel free to close or merge this.

**Comment by savingoyal** [comment]
@ruial That's good to hear. One issue that needs to be fixed for this PR is checking whether sha1sum is indeed available in the image -it is available for the default python image but might not be available in the image the user might be using as an override. This can be a potentially breaking change. Let's think through the universe of use cases we would want to support for code verification and we can resuscitate this PR after we have a good body of user stories.

**Pull request closed without merging**
