### PR TITLE
Remove vendored libs for Py 3.5 (not needed)

### PR DESCRIPTION
**Pull request by romain-intel**

### CODE REVIEW

**Review by savingoyal — CHANGES_REQUESTED** [review]
this PR drops support for Py3.5 from Metaflow and not just `@conda`

**Comment by romain-intel** [comment]
I am not sure why you are saying that? I just reverted the additions of the packages that were added to vendor_v3_5. See here: https://github.com/Netflix/metaflow/blame/d18be77c5f585307a7b31e6027a9605e43dc62a3/metaflow/_vendor/vendor_v3_5.txt

**Comment by romain-intel** [comment]
Ah, now I see. it doesn't find zipp from v3.5

**Comment by romain-intel** [comment]
Not sure what it did before. Let me check.

**Comment by romain-intel** [comment]
OK, there we go. zipp was floating before and when I committed I didn't see the directory because on the floating version, it has more stuff. I re-pinned to zipp 3.6.0 and should be fine now.

**Review by savingoyal — APPROVED** [review]

**Pull request merged**
