### PR TITLE
Support M1 Macs for `@conda`

### PR DESCRIPTION
**Pull request by savingoyal**

### CODE REVIEW

**Comment by savingoyal** [comment]
@hamelsmu What is the output of `platform.machine()` for the Python interpreter you are using to launch your flow? You might need to install Python 3.9.2 and ensure `platform.machine()` returns `amd64` for this to work.

**Comment by hamelsmu** [comment]
@savingoyal I'm using python `3.10.5`

```
> python -c "import platform; print(platform.machine())"
x86_64
```

**Comment by hamelsmu** [comment]
@savingoyal this works if you disable Rosetta for example `CONDA_SUBDIR=osx-arm64 mamba create -n pym1 python==3.9.2`

**Comment by hamelsmu** [comment]
Seems like this is OK to merge

**Review by hamelsmu — APPROVED** [review]

**Comment by savingoyal** [comment]
Great, I will merge as soon as tests pass.

**Pull request merged**
